import type { CountryTimeZoneData } from "../types/countryCurrencyInfo";

export const timeZoneInformation: Record<string, CountryTimeZoneData> = {
	AD: {
		id: "AD",
		name: "Andorra",
		timezones: ["Europe/Andorra"],
	},
	AE: {
		id: "AE",
		name: "United Arab Emirates",
		timezones: ["Asia/Dubai"],
	},
	AF: {
		id: "AF",
		name: "Afghanistan",
		timezones: ["Asia/Kabul"],
	},
	AG: {
		id: "AG",
		name: "Antigua and Barbuda",
		timezones: ["America/Puerto_Rico"],
	},
	AI: {
		id: "AI",
		name: "Anguilla",
		timezones: ["America/Puerto_Rico"],
	},
	AL: {
		id: "AL",
		name: "Albania",
		timezones: ["Europe/Tirane"],
	},
	AM: {
		id: "AM",
		name: "Armenia",
		timezones: ["Asia/Yerevan"],
	},
	AO: {
		id: "AO",
		name: "Angola",
		timezones: ["Africa/Lagos"],
	},
	AQ: {
		id: "AQ",
		name: "Antarctica",
		timezones: [
			"Antarctica/Casey",
			"Antarctica/Davis",
			"Antarctica/Mawson",
			"Antarctica/Palmer",
			"Antarctica/Rothera",
			"Antarctica/Troll",
			"Antarctica/Vostok",
			"Asia/Riyadh",
			"Asia/Singapore",
			"Pacific/Auckland",
			"Pacific/Port_Moresby",
		],
	},
	AR: {
		id: "AR",
		name: "Argentina",
		timezones: [
			"America/Argentina/Buenos_Aires",
			"America/Argentina/Catamarca",
			"America/Argentina/Cordoba",
			"America/Argentina/Jujuy",
			"America/Argentina/La_Rioja",
			"America/Argentina/Mendoza",
			"America/Argentina/Rio_Gallegos",
			"America/Argentina/Salta",
			"America/Argentina/San_Juan",
			"America/Argentina/San_Luis",
			"America/Argentina/Tucuman",
			"America/Argentina/Ushuaia",
		],
	},
	AS: {
		id: "AS",
		name: "American Samoa",
		timezones: ["Pacific/Pago_Pago"],
	},
	AT: {
		id: "AT",
		name: "Austria",
		timezones: ["Europe/Vienna"],
	},
	AU: {
		id: "AU",
		name: "Australia",
		timezones: [
			"Antarctica/Macquarie",
			"Asia/Tokyo",
			"Australia/Adelaide",
			"Australia/Brisbane",
			"Australia/Broken_Hill",
			"Australia/Darwin",
			"Australia/Eucla",
			"Australia/Hobart",
			"Australia/Lindeman",
			"Australia/Lord_Howe",
			"Australia/Melbourne",
			"Australia/Perth",
			"Australia/Sydney",
		],
	},
	AW: {
		id: "AW",
		name: "Aruba",
		timezones: ["America/Puerto_Rico"],
	},
	AX: {
		id: "AX",
		name: "Åland Islands",
		timezones: ["Europe/Helsinki"],
	},
	AZ: {
		id: "AZ",
		name: "Azerbaijan",
		timezones: ["Asia/Baku"],
	},
	BA: {
		id: "BA",
		name: "Bosnia and Herzegovina",
		timezones: ["Europe/Belgrade"],
	},
	BB: {
		id: "BB",
		name: "Barbados",
		timezones: ["America/Barbados"],
	},
	BD: {
		id: "BD",
		name: "Bangladesh",
		timezones: ["Asia/Dhaka"],
	},
	BE: {
		id: "BE",
		name: "Belgium",
		timezones: ["Europe/Brussels"],
	},
	BF: {
		id: "BF",
		name: "Burkina Faso",
		timezones: ["Africa/Abidjan"],
	},
	BG: {
		id: "BG",
		name: "Bulgaria",
		timezones: ["Europe/Sofia"],
	},
	BH: {
		id: "BH",
		name: "Bahrain",
		timezones: ["Asia/Qatar"],
	},
	BI: {
		id: "BI",
		name: "Burundi",
		timezones: ["Africa/Maputo"],
	},
	BJ: {
		id: "BJ",
		name: "Benin",
		timezones: ["Africa/Lagos"],
	},
	BL: {
		id: "BL",
		name: "Saint Barthélemy",
		timezones: ["America/Puerto_Rico"],
	},
	BM: {
		id: "BM",
		name: "Bermuda",
		timezones: ["Atlantic/Bermuda"],
	},
	BN: {
		id: "BN",
		name: "Brunei",
		timezones: ["Asia/Kuching"],
	},
	BO: {
		id: "BO",
		name: "Bolivia",
		timezones: ["America/La_Paz"],
	},
	BQ: {
		id: "BQ",
		name: "Caribbean Netherlands",
		timezones: ["America/Puerto_Rico"],
	},
	BR: {
		id: "BR",
		name: "Brazil",
		timezones: [
			"America/Araguaina",
			"America/Bahia",
			"America/Belem",
			"America/Boa_Vista",
			"America/Campo_Grande",
			"America/Cuiaba",
			"America/Eirunepe",
			"America/Fortaleza",
			"America/Maceio",
			"America/Manaus",
			"America/Noronha",
			"America/Porto_Velho",
			"America/Recife",
			"America/Rio_Branco",
			"America/Santarem",
			"America/Sao_Paulo",
		],
	},
	BS: {
		id: "BS",
		name: "Bahamas",
		timezones: ["America/Toronto"],
	},
	BT: {
		id: "BT",
		name: "Bhutan",
		timezones: ["Asia/Thimphu"],
	},
	BV: {
		id: "BV",
		name: "Bouvet Island",
		timezones: ["Europe/Berlin"],
	},
	BW: {
		id: "BW",
		name: "Botswana",
		timezones: ["Africa/Maputo"],
	},
	BY: {
		id: "BY",
		name: "Belarus",
		timezones: ["Europe/Minsk"],
	},
	BZ: {
		id: "BZ",
		name: "Belize",
		timezones: ["America/Belize"],
	},
	CA: {
		id: "CA",
		name: "Canada",
		timezones: [
			"America/Cambridge_Bay",
			"America/Dawson",
			"America/Dawson_Creek",
			"America/Edmonton",
			"America/Fort_Nelson",
			"America/Glace_Bay",
			"America/Goose_Bay",
			"America/Halifax",
			"America/Inuvik",
			"America/Iqaluit",
			"America/Moncton",
			"America/Panama",
			"America/Phoenix",
			"America/Puerto_Rico",
			"America/Rankin_Inlet",
			"America/Regina",
			"America/Resolute",
			"America/St_Johns",
			"America/Swift_Current",
			"America/Toronto",
			"America/Vancouver",
			"America/Whitehorse",
			"America/Winnipeg",
		],
	},
	CC: {
		id: "CC",
		name: "Cocos Islands",
		timezones: ["Asia/Yangon"],
	},
	CD: {
		id: "CD",
		name: "Democratic Republic of the Congo",
		timezones: ["Africa/Lagos", "Africa/Maputo"],
	},
	CF: {
		id: "CF",
		name: "Central African Republic",
		timezones: ["Africa/Lagos"],
	},
	CG: {
		id: "CG",
		name: "Republic of the Congo",
		timezones: ["Africa/Lagos"],
	},
	CH: {
		id: "CH",
		name: "Switzerland",
		timezones: ["Europe/Zurich"],
	},
	CI: {
		id: "CI",
		name: "Ivory Coast",
		timezones: ["Africa/Abidjan"],
	},
	CK: {
		id: "CK",
		name: "Cook Islands",
		timezones: ["Pacific/Rarotonga"],
	},
	CL: {
		id: "CL",
		name: "Chile",
		timezones: [
			"America/Coyhaique",
			"America/Punta_Arenas",
			"America/Santiago",
			"Pacific/Easter",
		],
	},
	CM: {
		id: "CM",
		name: "Cameroon",
		timezones: ["Africa/Lagos"],
	},
	CN: {
		id: "CN",
		name: "China",
		timezones: ["Asia/Shanghai", "Asia/Urumqi"],
	},
	CO: {
		id: "CO",
		name: "Colombia",
		timezones: ["America/Bogota"],
	},
	CR: {
		id: "CR",
		name: "Costa Rica",
		timezones: ["America/Costa_Rica"],
	},
	CU: {
		id: "CU",
		name: "Cuba",
		timezones: ["America/Havana"],
	},
	CV: {
		id: "CV",
		name: "Cabo Verde",
		timezones: ["Atlantic/Cape_Verde"],
	},
	CW: {
		id: "CW",
		name: "Curaçao",
		timezones: ["America/Puerto_Rico"],
	},
	CX: {
		id: "CX",
		name: "Christmas Island",
		timezones: ["Asia/Bangkok"],
	},
	CY: {
		id: "CY",
		name: "Cyprus",
		timezones: ["Asia/Famagusta", "Asia/Nicosia"],
	},
	CZ: {
		id: "CZ",
		name: "Czechia",
		timezones: ["Europe/Prague"],
	},
	DE: {
		id: "DE",
		name: "Germany",
		timezones: ["Europe/Berlin", "Europe/Zurich"],
	},
	DJ: {
		id: "DJ",
		name: "Djibouti",
		timezones: ["Africa/Nairobi"],
	},
	DK: {
		id: "DK",
		name: "Denmark",
		timezones: ["Europe/Berlin"],
	},
	DM: {
		id: "DM",
		name: "Dominica",
		timezones: ["America/Puerto_Rico"],
	},
	DO: {
		id: "DO",
		name: "Dominican Republic",
		timezones: ["America/Santo_Domingo"],
	},
	DZ: {
		id: "DZ",
		name: "Algeria",
		timezones: ["Africa/Algiers"],
	},
	EC: {
		id: "EC",
		name: "Ecuador",
		timezones: ["America/Guayaquil", "Pacific/Galapagos"],
	},
	EE: {
		id: "EE",
		name: "Estonia",
		timezones: ["Europe/Tallinn"],
	},
	EG: {
		id: "EG",
		name: "Egypt",
		timezones: ["Africa/Cairo"],
	},
	EH: {
		id: "EH",
		name: "Western Sahara",
		timezones: ["Africa/El_Aaiun"],
	},
	ER: {
		id: "ER",
		name: "Eritrea",
		timezones: ["Africa/Nairobi"],
	},
	ES: {
		id: "ES",
		name: "Spain",
		timezones: ["Africa/Ceuta", "Atlantic/Canary", "Europe/Madrid"],
	},
	ET: {
		id: "ET",
		name: "Ethiopia",
		timezones: ["Africa/Nairobi"],
	},
	FI: {
		id: "FI",
		name: "Finland",
		timezones: ["Europe/Helsinki"],
	},
	FJ: {
		id: "FJ",
		name: "Fiji",
		timezones: ["Pacific/Fiji"],
	},
	FK: {
		id: "FK",
		name: "Falkland Islands",
		timezones: ["Atlantic/Stanley"],
	},
	FM: {
		id: "FM",
		name: "Micronesia",
		timezones: [
			"Pacific/Guadalcanal",
			"Pacific/Kosrae",
			"Pacific/Port_Moresby",
		],
	},
	FO: {
		id: "FO",
		name: "Faroe Islands",
		timezones: ["Atlantic/Faroe"],
	},
	FR: {
		id: "FR",
		name: "France",
		timezones: ["Europe/Paris"],
	},
	GA: {
		id: "GA",
		name: "Gabon",
		timezones: ["Africa/Lagos"],
	},
	GB: {
		id: "GB",
		name: "United Kingdom",
		timezones: ["Europe/London"],
	},
	GD: {
		id: "GD",
		name: "Grenada",
		timezones: ["America/Puerto_Rico"],
	},
	GE: {
		id: "GE",
		name: "Georgia",
		timezones: ["Asia/Tbilisi"],
	},
	GF: {
		id: "GF",
		name: "French Guiana",
		timezones: ["America/Cayenne"],
	},
	GG: {
		id: "GG",
		name: "Guernsey",
		timezones: ["Europe/London"],
	},
	GH: {
		id: "GH",
		name: "Ghana",
		timezones: ["Africa/Abidjan"],
	},
	GI: {
		id: "GI",
		name: "Gibraltar",
		timezones: ["Europe/Gibraltar"],
	},
	GL: {
		id: "GL",
		name: "Greenland",
		timezones: [
			"America/Danmarkshavn",
			"America/Nuuk",
			"America/Scoresbysund",
			"America/Thule",
		],
	},
	GM: {
		id: "GM",
		name: "Gambia",
		timezones: ["Africa/Abidjan"],
	},
	GN: {
		id: "GN",
		name: "Guinea",
		timezones: ["Africa/Abidjan"],
	},
	GP: {
		id: "GP",
		name: "Guadeloupe",
		timezones: ["America/Puerto_Rico"],
	},
	GQ: {
		id: "GQ",
		name: "Equatorial Guinea",
		timezones: ["Africa/Lagos"],
	},
	GR: {
		id: "GR",
		name: "Greece",
		timezones: ["Europe/Athens"],
	},
	GS: {
		id: "GS",
		name: "South Georgia and the South Sandwich Islands",
		timezones: ["Atlantic/South_Georgia"],
	},
	GT: {
		id: "GT",
		name: "Guatemala",
		timezones: ["America/Guatemala"],
	},
	GU: {
		id: "GU",
		name: "Guam",
		timezones: ["Pacific/Guam"],
	},
	GW: {
		id: "GW",
		name: "Guinea-Bissau",
		timezones: ["Africa/Bissau"],
	},
	GY: {
		id: "GY",
		name: "Guyana",
		timezones: ["America/Guyana"],
	},
	HK: {
		id: "HK",
		name: "Hong Kong",
		timezones: ["Asia/Hong_Kong"],
	},
	HM: {
		id: "HM",
		name: "Heard Island and McDonald Islands",
		timezones: ["Indian/Maldives"],
	},
	HN: {
		id: "HN",
		name: "Honduras",
		timezones: ["America/Tegucigalpa"],
	},
	HR: {
		id: "HR",
		name: "Croatia",
		timezones: ["Europe/Belgrade"],
	},
	HT: {
		id: "HT",
		name: "Haiti",
		timezones: ["America/Port-au-Prince"],
	},
	HU: {
		id: "HU",
		name: "Hungary",
		timezones: ["Europe/Budapest"],
	},
	ID: {
		id: "ID",
		name: "Indonesia",
		timezones: [
			"Asia/Jakarta",
			"Asia/Jayapura",
			"Asia/Makassar",
			"Asia/Pontianak",
		],
	},
	IE: {
		id: "IE",
		name: "Ireland",
		timezones: ["Europe/Dublin"],
	},
	IL: {
		id: "IL",
		name: "Israel",
		timezones: ["Asia/Jerusalem"],
	},
	IM: {
		id: "IM",
		name: "Isle of Man",
		timezones: ["Europe/London"],
	},
	IN: {
		id: "IN",
		name: "India",
		timezones: ["Asia/Kolkata"],
	},
	IO: {
		id: "IO",
		name: "British Indian Ocean Territory",
		timezones: ["Indian/Chagos"],
	},
	IQ: {
		id: "IQ",
		name: "Iraq",
		timezones: ["Asia/Baghdad"],
	},
	IR: {
		id: "IR",
		name: "Iran",
		timezones: ["Asia/Tehran"],
	},
	IS: {
		id: "IS",
		name: "Iceland",
		timezones: ["Africa/Abidjan"],
	},
	IT: {
		id: "IT",
		name: "Italy",
		timezones: ["Europe/Rome"],
	},
	JE: {
		id: "JE",
		name: "Jersey",
		timezones: ["Europe/London"],
	},
	JM: {
		id: "JM",
		name: "Jamaica",
		timezones: ["America/Jamaica"],
	},
	JO: {
		id: "JO",
		name: "Jordan",
		timezones: ["Asia/Amman"],
	},
	JP: {
		id: "JP",
		name: "Japan",
		timezones: ["Asia/Tokyo"],
	},
	KE: {
		id: "KE",
		name: "Kenya",
		timezones: ["Africa/Nairobi"],
	},
	KG: {
		id: "KG",
		name: "Kyrgyzstan",
		timezones: ["Asia/Bishkek"],
	},
	KH: {
		id: "KH",
		name: "Cambodia",
		timezones: ["Asia/Bangkok"],
	},
	KI: {
		id: "KI",
		name: "Kiribati",
		timezones: ["Pacific/Kanton", "Pacific/Kiritimati", "Pacific/Tarawa"],
	},
	KM: {
		id: "KM",
		name: "Comoros",
		timezones: ["Africa/Nairobi"],
	},
	KN: {
		id: "KN",
		name: "Saint Kitts and Nevis",
		timezones: ["America/Puerto_Rico"],
	},
	KP: {
		id: "KP",
		name: "North Korea",
		timezones: ["Asia/Pyongyang"],
	},
	KR: {
		id: "KR",
		name: "South Korea",
		timezones: ["Asia/Seoul"],
	},
	KW: {
		id: "KW",
		name: "Kuwait",
		timezones: ["Asia/Riyadh"],
	},
	KY: {
		id: "KY",
		name: "Cayman Islands",
		timezones: ["America/Panama"],
	},
	KZ: {
		id: "KZ",
		name: "Kazakhstan",
		timezones: [
			"Asia/Almaty",
			"Asia/Aqtau",
			"Asia/Aqtobe",
			"Asia/Atyrau",
			"Asia/Oral",
			"Asia/Qostanay",
			"Asia/Qyzylorda",
		],
	},
	LA: {
		id: "LA",
		name: "Laos",
		timezones: ["Asia/Bangkok"],
	},
	LB: {
		id: "LB",
		name: "Lebanon",
		timezones: ["Asia/Beirut"],
	},
	LC: {
		id: "LC",
		name: "Saint Lucia",
		timezones: ["America/Puerto_Rico"],
	},
	LI: {
		id: "LI",
		name: "Liechtenstein",
		timezones: ["Europe/Zurich"],
	},
	LK: {
		id: "LK",
		name: "Sri Lanka",
		timezones: ["Asia/Colombo"],
	},
	LR: {
		id: "LR",
		name: "Liberia",
		timezones: ["Africa/Monrovia"],
	},
	LS: {
		id: "LS",
		name: "Lesotho",
		timezones: ["Africa/Johannesburg"],
	},
	LT: {
		id: "LT",
		name: "Lithuania",
		timezones: ["Europe/Vilnius"],
	},
	LU: {
		id: "LU",
		name: "Luxembourg",
		timezones: ["Europe/Brussels"],
	},
	LV: {
		id: "LV",
		name: "Latvia",
		timezones: ["Europe/Riga"],
	},
	LY: {
		id: "LY",
		name: "Libya",
		timezones: ["Africa/Tripoli"],
	},
	MA: {
		id: "MA",
		name: "Morocco",
		timezones: ["Africa/Casablanca"],
	},
	MC: {
		id: "MC",
		name: "Monaco",
		timezones: ["Europe/Paris"],
	},
	MD: {
		id: "MD",
		name: "Moldova",
		timezones: ["Europe/Chisinau"],
	},
	ME: {
		id: "ME",
		name: "Montenegro",
		timezones: ["Europe/Belgrade"],
	},
	MF: {
		id: "MF",
		name: "Saint Martin",
		timezones: ["America/Puerto_Rico"],
	},
	MG: {
		id: "MG",
		name: "Madagascar",
		timezones: ["Africa/Nairobi"],
	},
	MH: {
		id: "MH",
		name: "Marshall Islands",
		timezones: ["Pacific/Kwajalein", "Pacific/Tarawa"],
	},
	MK: {
		id: "MK",
		name: "North Macedonia",
		timezones: ["Europe/Belgrade"],
	},
	ML: {
		id: "ML",
		name: "Mali",
		timezones: ["Africa/Abidjan"],
	},
	MM: {
		id: "MM",
		name: "Myanmar",
		timezones: ["Asia/Yangon"],
	},
	MN: {
		id: "MN",
		name: "Mongolia",
		timezones: ["Asia/Hovd", "Asia/Ulaanbaatar"],
	},
	MO: {
		id: "MO",
		name: "Macao",
		timezones: ["Asia/Macau"],
	},
	MP: {
		id: "MP",
		name: "Northern Mariana Islands",
		timezones: ["Pacific/Guam"],
	},
	MQ: {
		id: "MQ",
		name: "Martinique",
		timezones: ["America/Martinique"],
	},
	MR: {
		id: "MR",
		name: "Mauritania",
		timezones: ["Africa/Abidjan"],
	},
	MS: {
		id: "MS",
		name: "Montserrat",
		timezones: ["America/Puerto_Rico"],
	},
	MT: {
		id: "MT",
		name: "Malta",
		timezones: ["Europe/Malta"],
	},
	MU: {
		id: "MU",
		name: "Mauritius",
		timezones: ["Indian/Mauritius"],
	},
	MV: {
		id: "MV",
		name: "Maldives",
		timezones: ["Indian/Maldives"],
	},
	MW: {
		id: "MW",
		name: "Malawi",
		timezones: ["Africa/Maputo"],
	},
	MX: {
		id: "MX",
		name: "Mexico",
		timezones: [
			"America/Bahia_Banderas",
			"America/Cancun",
			"America/Chihuahua",
			"America/Ciudad_Juarez",
			"America/Hermosillo",
			"America/Matamoros",
			"America/Mazatlan",
			"America/Merida",
			"America/Mexico_City",
			"America/Monterrey",
			"America/Ojinaga",
			"America/Tijuana",
		],
	},
	MY: {
		id: "MY",
		name: "Malaysia",
		timezones: ["Asia/Kuching", "Asia/Singapore"],
	},
	MZ: {
		id: "MZ",
		name: "Mozambique",
		timezones: ["Africa/Maputo"],
	},
	NA: {
		id: "NA",
		name: "Namibia",
		timezones: ["Africa/Windhoek"],
	},
	NC: {
		id: "NC",
		name: "New Caledonia",
		timezones: ["Pacific/Noumea"],
	},
	NE: {
		id: "NE",
		name: "Niger",
		timezones: ["Africa/Lagos"],
	},
	NF: {
		id: "NF",
		name: "Norfolk Island",
		timezones: ["Pacific/Norfolk"],
	},
	NG: {
		id: "NG",
		name: "Nigeria",
		timezones: ["Africa/Lagos"],
	},
	NI: {
		id: "NI",
		name: "Nicaragua",
		timezones: ["America/Managua"],
	},
	NL: {
		id: "NL",
		name: "Netherlands",
		timezones: ["Europe/Brussels"],
	},
	NO: {
		id: "NO",
		name: "Norway",
		timezones: ["Europe/Berlin"],
	},
	NP: {
		id: "NP",
		name: "Nepal",
		timezones: ["Asia/Kathmandu"],
	},
	NR: {
		id: "NR",
		name: "Nauru",
		timezones: ["Pacific/Nauru"],
	},
	NU: {
		id: "NU",
		name: "Niue",
		timezones: ["Pacific/Niue"],
	},
	NZ: {
		id: "NZ",
		name: "New Zealand",
		timezones: ["Pacific/Auckland", "Pacific/Chatham"],
	},
	OM: {
		id: "OM",
		name: "Oman",
		timezones: ["Asia/Dubai"],
	},
	PA: {
		id: "PA",
		name: "Panama",
		timezones: ["America/Panama"],
	},
	PE: {
		id: "PE",
		name: "Peru",
		timezones: ["America/Lima"],
	},
	PF: {
		id: "PF",
		name: "French Polynesia",
		timezones: ["Pacific/Gambier", "Pacific/Marquesas", "Pacific/Tahiti"],
	},
	PG: {
		id: "PG",
		name: "Papua New Guinea",
		timezones: ["Pacific/Bougainville", "Pacific/Port_Moresby"],
	},
	PH: {
		id: "PH",
		name: "Philippines",
		timezones: ["Asia/Manila"],
	},
	PK: {
		id: "PK",
		name: "Pakistan",
		timezones: ["Asia/Karachi"],
	},
	PL: {
		id: "PL",
		name: "Poland",
		timezones: ["Europe/Warsaw"],
	},
	PM: {
		id: "PM",
		name: "Saint Pierre and Miquelon",
		timezones: ["America/Miquelon"],
	},
	PN: {
		id: "PN",
		name: "Pitcairn",
		timezones: ["Pacific/Pitcairn"],
	},
	PR: {
		id: "PR",
		name: "Puerto Rico",
		timezones: ["America/Puerto_Rico"],
	},
	PS: {
		id: "PS",
		name: "Palestine",
		timezones: ["Asia/Gaza", "Asia/Hebron"],
	},
	PT: {
		id: "PT",
		name: "Portugal",
		timezones: ["Atlantic/Azores", "Atlantic/Madeira", "Europe/Lisbon"],
	},
	PW: {
		id: "PW",
		name: "Palau",
		timezones: ["Pacific/Palau"],
	},
	PY: {
		id: "PY",
		name: "Paraguay",
		timezones: ["America/Asuncion"],
	},
	QA: {
		id: "QA",
		name: "Qatar",
		timezones: ["Asia/Qatar"],
	},
	RE: {
		id: "RE",
		name: "Réunion",
		timezones: ["Asia/Dubai"],
	},
	RO: {
		id: "RO",
		name: "Romania",
		timezones: ["Europe/Bucharest"],
	},
	RS: {
		id: "RS",
		name: "Serbia",
		timezones: ["Europe/Belgrade"],
	},
	RU: {
		id: "RU",
		name: "Russia",
		timezones: [
			"Asia/Anadyr",
			"Asia/Barnaul",
			"Asia/Chita",
			"Asia/Irkutsk",
			"Asia/Kamchatka",
			"Asia/Khandyga",
			"Asia/Krasnoyarsk",
			"Asia/Magadan",
			"Asia/Novokuznetsk",
			"Asia/Novosibirsk",
			"Asia/Omsk",
			"Asia/Sakhalin",
			"Asia/Srednekolymsk",
			"Asia/Tomsk",
			"Asia/Ust-Nera",
			"Asia/Vladivostok",
			"Asia/Yakutsk",
			"Asia/Yekaterinburg",
			"Europe/Astrakhan",
			"Europe/Kaliningrad",
			"Europe/Kirov",
			"Europe/Moscow",
			"Europe/Samara",
			"Europe/Saratov",
			"Europe/Simferopol",
			"Europe/Ulyanovsk",
			"Europe/Volgograd",
		],
	},
	RW: {
		id: "RW",
		name: "Rwanda",
		timezones: ["Africa/Maputo"],
	},
	SA: {
		id: "SA",
		name: "Saudi Arabia",
		timezones: ["Asia/Riyadh"],
	},
	SB: {
		id: "SB",
		name: "Solomon Islands",
		timezones: ["Pacific/Guadalcanal"],
	},
	SC: {
		id: "SC",
		name: "Seychelles",
		timezones: ["Asia/Dubai"],
	},
	SD: {
		id: "SD",
		name: "Sudan",
		timezones: ["Africa/Khartoum"],
	},
	SE: {
		id: "SE",
		name: "Sweden",
		timezones: ["Europe/Berlin"],
	},
	SG: {
		id: "SG",
		name: "Singapore",
		timezones: ["Asia/Singapore"],
	},
	SH: {
		id: "SH",
		name: "Saint Helena, Ascension and Tristan da Cunha",
		timezones: ["Africa/Abidjan"],
	},
	SI: {
		id: "SI",
		name: "Slovenia",
		timezones: ["Europe/Belgrade"],
	},
	SJ: {
		id: "SJ",
		name: "Svalbard and Jan Mayen",
		timezones: ["Europe/Berlin"],
	},
	SK: {
		id: "SK",
		name: "Slovakia",
		timezones: ["Europe/Prague"],
	},
	SL: {
		id: "SL",
		name: "Sierra Leone",
		timezones: ["Africa/Abidjan"],
	},
	SM: {
		id: "SM",
		name: "San Marino",
		timezones: ["Europe/Rome"],
	},
	SN: {
		id: "SN",
		name: "Senegal",
		timezones: ["Africa/Abidjan"],
	},
	SO: {
		id: "SO",
		name: "Somalia",
		timezones: ["Africa/Nairobi"],
	},
	SR: {
		id: "SR",
		name: "Suriname",
		timezones: ["America/Paramaribo"],
	},
	SS: {
		id: "SS",
		name: "South Sudan",
		timezones: ["Africa/Juba"],
	},
	ST: {
		id: "ST",
		name: "Sao Tome and Principe",
		timezones: ["Africa/Sao_Tome"],
	},
	SV: {
		id: "SV",
		name: "El Salvador",
		timezones: ["America/El_Salvador"],
	},
	SX: {
		id: "SX",
		name: "Sint Maarten",
		timezones: ["America/Puerto_Rico"],
	},
	SY: {
		id: "SY",
		name: "Syria",
		timezones: ["Asia/Damascus"],
	},
	SZ: {
		id: "SZ",
		name: "Eswatini",
		timezones: ["Africa/Johannesburg"],
	},
	TC: {
		id: "TC",
		name: "Turks and Caicos Islands",
		timezones: ["America/Grand_Turk"],
	},
	TD: {
		id: "TD",
		name: "Chad",
		timezones: ["Africa/Ndjamena"],
	},
	TF: {
		id: "TF",
		name: "French Southern Territories",
		timezones: ["Asia/Dubai", "Indian/Maldives"],
	},
	TG: {
		id: "TG",
		name: "Togo",
		timezones: ["Africa/Abidjan"],
	},
	TH: {
		id: "TH",
		name: "Thailand",
		timezones: ["Asia/Bangkok"],
	},
	TJ: {
		id: "TJ",
		name: "Tajikistan",
		timezones: ["Asia/Dushanbe"],
	},
	TK: {
		id: "TK",
		name: "Tokelau",
		timezones: ["Pacific/Fakaofo"],
	},
	TL: {
		id: "TL",
		name: "Timor-Leste",
		timezones: ["Asia/Dili"],
	},
	TM: {
		id: "TM",
		name: "Turkmenistan",
		timezones: ["Asia/Ashgabat"],
	},
	TN: {
		id: "TN",
		name: "Tunisia",
		timezones: ["Africa/Tunis"],
	},
	TO: {
		id: "TO",
		name: "Tonga",
		timezones: ["Pacific/Tongatapu"],
	},
	TR: {
		id: "TR",
		name: "Türkiye",
		timezones: ["Europe/Istanbul"],
	},
	TT: {
		id: "TT",
		name: "Trinidad and Tobago",
		timezones: ["America/Puerto_Rico"],
	},
	TV: {
		id: "TV",
		name: "Tuvalu",
		timezones: ["Pacific/Tarawa"],
	},
	TW: {
		id: "TW",
		name: "Taiwan",
		timezones: ["Asia/Taipei"],
	},
	TZ: {
		id: "TZ",
		name: "Tanzania",
		timezones: ["Africa/Nairobi"],
	},
	UA: {
		id: "UA",
		name: "Ukraine",
		timezones: ["Europe/Kyiv", "Europe/Simferopol"],
	},
	UG: {
		id: "UG",
		name: "Uganda",
		timezones: ["Africa/Nairobi"],
	},
	UM: {
		id: "UM",
		name: "United States Minor Outlying Islands",
		timezones: ["Pacific/Pago_Pago", "Pacific/Tarawa"],
	},
	US: {
		id: "US",
		name: "United States of America",
		timezones: [
			"America/Adak",
			"America/Anchorage",
			"America/Boise",
			"America/Chicago",
			"America/Denver",
			"America/Detroit",
			"America/Indiana/Indianapolis",
			"America/Indiana/Knox",
			"America/Indiana/Marengo",
			"America/Indiana/Petersburg",
			"America/Indiana/Tell_City",
			"America/Indiana/Vevay",
			"America/Indiana/Vincennes",
			"America/Indiana/Winamac",
			"America/Juneau",
			"America/Kentucky/Louisville",
			"America/Kentucky/Monticello",
			"America/Los_Angeles",
			"America/Menominee",
			"America/Metlakatla",
			"America/New_York",
			"America/Nome",
			"America/North_Dakota/Beulah",
			"America/North_Dakota/Center",
			"America/North_Dakota/New_Salem",
			"America/Phoenix",
			"America/Sitka",
			"America/Yakutat",
			"Pacific/Honolulu",
		],
	},
	UY: {
		id: "UY",
		name: "Uruguay",
		timezones: ["America/Montevideo"],
	},
	UZ: {
		id: "UZ",
		name: "Uzbekistan",
		timezones: ["Asia/Samarkand", "Asia/Tashkent"],
	},
	VA: {
		id: "VA",
		name: "Holy See",
		timezones: ["Europe/Rome"],
	},
	VC: {
		id: "VC",
		name: "Saint Vincent and the Grenadines",
		timezones: ["America/Puerto_Rico"],
	},
	VE: {
		id: "VE",
		name: "Venezuela",
		timezones: ["America/Caracas"],
	},
	VG: {
		id: "VG",
		name: "Virgin Islands (UK)",
		timezones: ["America/Puerto_Rico"],
	},
	VI: {
		id: "VI",
		name: "Virgin Islands (US)",
		timezones: ["America/Puerto_Rico"],
	},
	VN: {
		id: "VN",
		name: "Vietnam",
		timezones: ["Asia/Bangkok", "Asia/Ho_Chi_Minh"],
	},
	VU: {
		id: "VU",
		name: "Vanuatu",
		timezones: ["Pacific/Efate"],
	},
	WF: {
		id: "WF",
		name: "Wallis and Futuna",
		timezones: ["Pacific/Tarawa"],
	},
	WS: {
		id: "WS",
		name: "Samoa",
		timezones: ["Pacific/Apia"],
	},
	XK: {
		id: "XK",
		name: "Kosovo",
		timezones: ["Europe/Berlin", "Europe/Zurich"],
	},
	YE: {
		id: "YE",
		name: "Yemen",
		timezones: ["Asia/Riyadh"],
	},
	YT: {
		id: "YT",
		name: "Mayotte",
		timezones: ["Africa/Nairobi"],
	},
	ZA: {
		id: "ZA",
		name: "South Africa",
		timezones: ["Africa/Johannesburg"],
	},
	ZM: {
		id: "ZM",
		name: "Zambia",
		timezones: ["Africa/Maputo"],
	},
	ZW: {
		id: "ZW",
		name: "Zimbabwe",
		timezones: ["Africa/Maputo"],
	},
};
